-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"

-- Monitor
hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
    mirror = "eDP-1",
})

-- Variables de entorno NVIDIA
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")

-- Tema de cursor (Bibata-Modern-Ice: blanco, mejor contraste sobre el fondo
-- oscuro #0f0f0f que la variante Classic negra) - instalar con
-- `yay -S bibata-cursor-theme` si "hyprctl reload" no lo aplica.
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

-- Reglas de capas (layer-shell)
-- NOTA: el conversor tenía un bug aquí (metía literalmente "match:namespace ..."
-- como valor del campo namespace, en vez de solo el regex) - corregido a mano.
-- El campo "blur" (bool plano) está CONFIRMADO: probado con
-- `Hyprland --config hyprland.lua --verify-config` en 0.56.2, que sí detecta
-- nombres de campo inventados ("unknown field") - blur pasó limpio.
hl.layer_rule({
    match = { namespace = "^(swaync-control-center)$" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "^(rofi)$" },
    blur = false,
})

-- media-card.py es GtkLayerShell con fondo rgba (0.92) - mismo bug de blur+alpha
-- en NVIDIA que control-center: con blur true se ve un borde rectangular feo
-- alrededor de las esquinas redondeadas (confirmado por Tara 2026-09-08, mismo
-- síntoma que se preveía en la nota original de 2026-08-26). Quitado el blur,
-- igual que se hizo con control-center el mismo día que se encontró el bug.

-- Reglas de ventanas
hl.window_rule({
    match = {
        class = "^(xfreerdp)$",
    },
    workspace = "9",
})

-- "silent" no aparece documentado en ningún sitio para el campo workspace de
-- window_rule. `--verify-config` acepta el string tal cual (workspace es solo
-- un campo "string", no valida su contenido), así que esto NO confirma que
-- Hyprland interprete "silent" de verdad - solo que el texto es sintácticamente
-- válido. Falta probarlo en vivo (¿se mueve sin cambiar de escritorio, o no?).
hl.window_rule({
    match = {
        class = "^(rdp-console)$",
    },
    workspace = "special:minimized silent",
})

hl.window_rule({
    match = {
        class = "^notarapida$",
    },
    float = true,
    size = "700 480",
    center = true,
})

hl.window_rule({
    match = {
        class = "^xfce-polkit$",
    },
    float = true,
    size = "520 143",
    center = true,
})

hl.window_rule({
    match = {
        class = "^(fsearch|io.github.cboxdoerfer.FSearch)$",
    },
    float = true,
    size = "850 550",
    center = true,
})

hl.window_rule({
    match = {
        title = "^(.*(Abrir archivo|Guardar como|Open File|Save As|Confirmar|Confirm|Elección de archivo|Sign in - Google Accounts|Iniciar sesión).*)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal.*|zenity|pavucontrol|blueman-manager)$",
    },
    float = true,
})

-- Picture-in-Picture de Firefox: flotante, fijada sobre todo y en la esquina
-- inferior derecha (para seguir una clase mientras trabajas en otra ventana).
hl.window_rule({
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
    pin = true,
    size = "480 270",
    move = "100%-500 100%-290",
})

-- Input

hl.config({
    input = {
        kb_layout = "es",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
        },
    },
})

-- Apariencia general
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 0,
        col = {
            active_border = "rgba(00000000)",
            inactive_border = "rgba(00000000)",
        },
    },
})

-- Borde degradado solo en la terminal
hl.window_rule({
    match = { class = "^(kitty)$" },
    border_size = 2,
    border_color = "rgba(ff9e64ff) rgba(bb9af7ff) 45deg rgba(2d2d2d55)",
})


hl.config({
    dwindle = {
        -- pseudotile se elimino como opcion global en Hyprland 0.55 - ahora es
        -- por ventana (dispatcher "pseudo" o windowrule = pseudo). No hace falta
        -- aqui: notarapida y xfce-polkit ya tienen windowrule con size explicito.
        preserve_split = true, -- no reordena el resto de ventanas al cerrar una
        -- smart_split en realidad NO decide por proporción de la ventana (ese
        -- comentario era incorrecto) - decide por la posición exacta del cursor
        -- dentro de la ventana, de ahi la sensacion de "aleatorio" arriba/abajo.
        -- Desactivado: sin smart_split, Hyprland decide por ancho vs alto de la
        -- ventana (en este portatil casi siempre mas ancha que alta -> lateral
        -- por defecto). Super+J sigue disponible para forzar el otro sentido.
        smart_split = false,
    },
})

hl.config({
    misc = {
        -- vfr se movio a debug:vfr en 0.55 - la propia doc de Hyprland dice que
        -- es una opcion de debug, "no deberia tocarse en produccion". No se fija.
        vrr = 1, -- VRR solo en fullscreen si el panel lo soporta de verdad - inofensivo si no lo soporta
    },
})

hl.config({
    render = {
        direct_scanout = false,
    },
})

hl.config({
    decoration = {
        rounding = 12,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        blur = {
            enabled = true,
            size = 5,
            passes = 3,
            new_optimizations = true,
            xray = false,
            noise = 0.0,
            contrast = 1.15,
            brightness = 0.60,
            vibrancy = 0.10,
            vibrancy_darkness = 0.10,
        },
        shadow = {
            enabled = true,
            range = 20,
            render_power = 3,
            color = "rgba(00000066)",
        },
    },
})

-- =============================================================================
-- ANIMACIONES CINEMÁTICAS (OPTIMIZADAS A 144Hz)
-- =============================================================================
hl.curve("md3_decel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1.0 } } })
hl.curve("md3_accel", { type = "bezier", points = { { 0.3, 0.0 }, { 0.8, 0.15 } } })

hl.config({
    animations = {
        enabled = true,
    },
})

-- Ventanas: entrada suave cinematográfica con popin a 144Hz
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 2.5,
    bezier = "md3_decel",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 2.5,
    bezier = "md3_decel",
    style = "popin 90%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 2.0,
    bezier = "md3_accel",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 2.5,
    bezier = "md3_decel",
})
-- Fades y capas (Waybar, menús, popups)
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 2.2,
    bezier = "md3_decel",
})
hl.animation({
    leaf = "fadeDim",
    enabled = false,
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 2.5,
    bezier = "md3_decel",
    style = "slide",
})
-- Escritorios: transición slidefade suave a 144Hz
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 3.8,
    bezier = "md3_decel",
    style = "slidefade 15%",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 3.5,
    bezier = "md3_decel",
    style = "slidevert",
})
-- Bordes
hl.animation({
    leaf = "border",
    enabled = false,
})

-- Ratón
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
hl.bind("ALT + mouse:272", hl.dsp.window.drag())
hl.bind("ALT + mouse:273", hl.dsp.window.resize())
hl.bind(mainMod .. " + mouse:274", hl.dsp.exec_cmd("/home/tara/.local/bin/workspace-picker.sh"))

-- Aplicaciones
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("~/.local/bin/nota-rapida.sh"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd("rofi -show drun -theme ~/.config/rofi/launcher.rasi"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("/home/tara/.local/bin/control-center.py"))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("/home/tara/.local/bin/show-keybindings.sh"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("/home/tara/.local/bin/bluetooth-menu.sh"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("wasistlos"))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("/home/tara/.local/bin/ssh-launcher.sh"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("/home/tara/.local/bin/seclists"))
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd("/home/tara/.local/bin/zen-mode"))
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd("/home/tara/.local/bin/buscar-vault"))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("/home/tara/.local/bin/repos"))
hl.bind(mainMod .. " + H", hl.dsp.exec_cmd("/home/tara/.local/bin/identificar-hash --rofi"))
hl.bind(mainMod .. " + ALT + W", hl.dsp.exec_cmd("/home/tara/.local/bin/wallpaper-picker.sh"))
hl.bind(mainMod .. " + ALT + C", hl.dsp.exec_cmd("/home/tara/.local/bin/change-cursor.sh"))
hl.bind(mainMod .. " + ALT + P", hl.dsp.exec_cmd("/home/tara/.local/bin/set-system-mode.sh"))

-- Bloquear pantalla y apagado
hl.bind(mainMod .. " + ALT + L", hl.dsp.exec_cmd("/home/tara/.local/bin/hyprlock-launch.sh"))
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("/home/tara/.local/bin/power-menu.sh"))

-- Ventanas
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + SHIFT + Space", hl.dsp.exec_cmd("/home/tara/.local/bin/toggle-floating.sh"))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("/home/tara/.local/bin/toggle-floating.sh"))
hl.bind(mainMod .. " + CTRL + M", hl.dsp.exit())
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload && notify-send \"Hyprland\" \"Config recargado\""))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("/home/tara/.local/bin/compact-workspaces.sh"))

-- Foco entre ventanas (Super + Ctrl + Flechas)
hl.bind(mainMod .. " + CTRL + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + CTRL + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + CTRL + down", hl.dsp.focus({ direction = "down" }))

-- Mover ventanas (Super + Ctrl + Shift + Flechas)
hl.bind(mainMod .. " + CTRL + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + CTRL + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + CTRL + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + CTRL + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

-- Redimensionar ventanas (Super + Alt + Flechas)
hl.bind(mainMod .. " + ALT + left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
hl.bind(mainMod .. " + ALT + right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
hl.bind(mainMod .. " + ALT + up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
hl.bind(mainMod .. " + ALT + down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

-- Workspaces
hl.bind("ALT + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("ALT + left", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("ALT + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("ALT + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("ALT + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("ALT + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("ALT + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("ALT + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("ALT + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("ALT + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("ALT + 9", hl.dsp.focus({ workspace = 9 }))

-- Mover ventana a workspace
hl.bind("ALT + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("ALT + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("ALT + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("ALT + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("ALT + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("ALT + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("ALT + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("ALT + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("ALT + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))

-- Volumen (con feedback visual OSD y respaldo directo en PipeWire)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise || wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower || wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle || wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle || wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

-- Música (l = funciona con pantalla bloqueada)
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Brillo (Fn+F7/F8 en el ROG con feedback OSD y respaldo directo)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness raise || brightnessctl set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness lower || brightnessctl set 5%-"), { locked = true, repeating = true })

-- Bloqueo de mayúsculas (Caps Lock OSD)
hl.bind("Caps_Lock", hl.dsp.exec_cmd("swayosd-client --caps-lock"), { release = true })

-- LEDs teclado ROG: brillo (Super+Shift+flechas arriba/abajo)
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.exec_cmd("sudo /home/tara/.local/bin/kbd-brightness.sh up"), { locked = true, repeating = true })
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.exec_cmd("sudo /home/tara/.local/bin/kbd-brightness.sh down"), { locked = true, repeating = true })

-- Screenshot
hl.bind("Print", hl.dsp.exec_cmd("/home/tara/.local/bin/screenshot.sh"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("/home/tara/.local/bin/screenshot.sh"))

-- Desactivar la red (FN+F12)
hl.bind("XF86RFKill", hl.dsp.exec_cmd("sudo /usr/local/bin/toggle-network.sh"), { locked = true })

-- VPN sola
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("/usr/local/bin/toggle-vpn.sh"))

-- Portapapeles (historial)
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu -p \"󰅍 \" -theme ~/.config/rofi/clipboard.rasi | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + CTRL + V", hl.dsp.exec_cmd("pkill -x wl-paste; rm -f \"${XDG_CACHE_HOME:-$HOME/.cache}/cliphist/db\"; wl-paste --watch cliphist store & notify-send \"Portapapeles\" \"Historial reiniciado\" -i edit-clear"))
-- VPN + RDP a Windows 11 (FN+F10)
hl.bind("XF86TouchpadToggle", hl.dsp.exec_cmd("kitty --class rdp-console --title \"RDP Console\" -e /home/tara/.local/bin/toggle-vpn-rdp.sh"))

-- Modo RDP: rdp-mode-watch.py activa este submap automaticamente en
-- cuanto la ventana xfreerdp coge el foco (y lo quita al perderlo), asi
-- las teclas viajan directas a Windows sin tener que pulsar nada antes.
-- Excepciones que se quedan en Hyprland: SUPER+Q (matar la ventana si
-- se cuelga) y ALT+numeros/flechas (cambiar de escritorio). Control_r
-- es un escape manual por si el vigia se cae.
hl.define_submap("rdp", function()
    hl.bind("control_r", hl.dsp.submap("reset"))
    hl.bind("control_r", hl.dsp.exec_cmd("/home/tara/.local/bin/rdp-mode.sh off"))
    hl.bind(mainMod .. " + Q", hl.dsp.window.close())
    hl.bind("ALT + 1", hl.dsp.focus({ workspace = 1 }))
    hl.bind("ALT + 2", hl.dsp.focus({ workspace = 2 }))
    hl.bind("ALT + 3", hl.dsp.focus({ workspace = 3 }))
    hl.bind("ALT + 4", hl.dsp.focus({ workspace = 4 }))
    hl.bind("ALT + 5", hl.dsp.focus({ workspace = 5 }))
    hl.bind("ALT + 6", hl.dsp.focus({ workspace = 6 }))
    hl.bind("ALT + 7", hl.dsp.focus({ workspace = 7 }))
    hl.bind("ALT + 8", hl.dsp.focus({ workspace = 8 }))
    hl.bind("ALT + 9", hl.dsp.focus({ workspace = 9 }))
    hl.bind("ALT + right", hl.dsp.focus({ workspace = "e+1" }))
    hl.bind("ALT + left", hl.dsp.focus({ workspace = "e-1" }))
end)

-- Fondos de pantalla
hl.bind(mainMod .. " + right", hl.dsp.exec_cmd("/home/tara/.local/bin/wallpaper-cycle.sh next"))
hl.bind(mainMod .. " + left", hl.dsp.exec_cmd("/home/tara/.local/bin/wallpaper-cycle.sh prev"))

-- Apps rápidas
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("discord"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("spotify-launcher"))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("obsidian"))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("telegram-desktop"))
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("keepassxc"))

-- Pantalla completa
hl.bind(mainMod .. " + F11", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F11", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))

-- Ocultar/recuperar ventana (pseudo-minimizar)
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.window.move({ workspace = "special:minimized" }))
hl.bind(mainMod .. " + N", hl.dsp.workspace.toggle_special("minimized"))
hl.bind(mainMod .. " + CTRL + N", hl.dsp.window.move({ workspace = "previous" }))

-- Cambiar entre ventanas
-- El conversor había inventado un campo "prev" para el ciclo inverso que no
-- existe en la API (solo hay "next": bool) - corregido a next = false.
hl.bind("ALT + Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind("ALT + SHIFT + Tab", hl.dsp.window.cycle_next({ next = false }))

-- Autostart
-- Arranque secuencial: Hyprlock cubre la pantalla antes de cargar el wallpaper.
hl.on("hyprland.start", function()
    hl.exec_cmd("/home/tara/.local/bin/hyprland-startup-lock.sh")
    hl.exec_cmd("/home/tara/.local/bin/change-cursor.sh apply")
    hl.exec_cmd("/home/tara/.local/bin/auto-battery-watcher.sh")
    hl.exec_cmd("/home/tara/.local/bin/auto-network-watcher.sh")
    hl.exec_cmd("waybar")
    hl.exec_cmd("/usr/lib/xfce-polkit/xfce-polkit")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("swaync")
    hl.exec_cmd("systemctl --user start swayosd.service")
    hl.exec_cmd("/home/tara/.local/bin/lanmouse-autostart.sh")
    hl.exec_cmd("python3 /home/tara/.local/bin/rdp-mode-watch.py")
    hl.exec_cmd("/home/tara/.local/bin/notification-daemon.py")
end)

