# Tokyo Night (warm — sin azules)
background            #0f0f0f
foreground            #c9c9c9
selection_background  #2d2d2d
selection_foreground  #ffffff
cursor                #ff9e64
cursor_text_color     #0f0f0f

# Colores ANSI
color0   #2d2d2d
color1   #e05f78
color2   #9ece6a
color3   #e0af68
color4   #ff9e64
color5   #9d7cd8
color6   #787c99
color7   #c9c9c9

# Colores Bright
color8   #4e5173
color9   #ff7a93
color10  #b9f27c
color11  #ffc777
color12  #ffb88c
color13  #c099ff
color14  #a9b1d6
color15  #ffffff

shell /bin/zsh
shell_integration enabled

# Pestañas
tab_bar_style              powerline
tab_powerline_style        slanted
tab_bar_edge               top
tab_bar_min_tabs           2
tab_title_template         " {index}: {title} "
active_tab_foreground      #0f0f0f
active_tab_background      #ff9e64
active_tab_font_style      bold
inactive_tab_foreground    #c9c9c9
inactive_tab_background    #2d2d2d
inactive_tab_font_style    normal
tab_bar_background         #0f0f0f

# Fuente
font_family      JetBrainsMono Nerd Font
font_size        12.0

# Transparencia
background_opacity 0.65

# Sin bordes, aspecto limpio
hide_window_decorations yes
window_padding_width 10

# Atajos de Portapapeles y Pestañas
map ctrl+v paste_from_clipboard
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab
map ctrl+backspace send_text all \x17

# Selección estilo PuTTY y permisos de portapapeles OSC 52
copy_on_select yes
clipboard_control write-clipboard write-primary read-clipboard read-primary
mouse_map right click ungrabbed paste_from_selection

# Desactivar campanas y notificaciones de terminal
enable_audio_bell no
window_alert_on_bell no
notify_on_cmd_finish never
